Update README.zh-Hans.md
Genymobile/scrcpy pull request #3126
Opened 2022-03-18 03:54 UTC by epiciskandar

Fix misleading zoom instruction, which gave opposite action steps.

操作说明写反了，造成误导。

2022-03-18 07:46 UTC, rom1v commented
cc @Win7GM @yume-chan

2022-03-18 08:48 UTC, yume-chan reviewed
The old translation is not like common Chinese, so I'd like the whole part to be improved.

2022-03-18 08:48 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
I think this part can be phased better, for example something like

```diff
- 模拟“双指缩放”：<kbd>Ctrl</kbd>+_按住并移动鼠标_。
+ 模拟“双指缩放”：<kbd>Ctrl</kbd>+_按下并拖动鼠标_。

- 更准确的说，在按住 <kbd>Ctrl</kbd> 时按下鼠标左键。直到松开鼠标左键，所有鼠标移动将以屏幕中心为原点，缩放或旋转内容 (如果应用支持)。
+ 准确的说，按住 <kbd>Ctrl</kbd>，然后按下鼠标左键。在松开鼠标左键前，移动鼠标会使屏幕内容相对于屏幕中心缩放或旋转 (如果应用支持)。

- 实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
+ 具体来说，_scrcpy_ 会在鼠标位置关于屏幕中心对称的位置上再生成一个“虚拟手指”。
```

2022-03-18 09:29 UTC, Win7GM requested changes

2022-03-18 09:29 UTC, Win7GM commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
> I think this part can be phased better, for example something like
> 
> ```diff
> - 模拟“双指缩放”：<kbd>Ctrl</kbd>+_按住并移动鼠标_。
> + 模拟“双指缩放”：<kbd>Ctrl</kbd>+_按下并拖动鼠标_。
> 
> - 更准确的说，在按住 <kbd>Ctrl</kbd> 时按下鼠标左键。直到松开鼠标左键，所有鼠标移动将以屏幕中心为原点，缩放或旋转内容 (如果应用支持)。
> + 准确的说，按住 <kbd>Ctrl</kbd>，然后按下鼠标左键。在松开鼠标左键前，移动鼠标会使屏幕内容相对于屏幕中心缩放或旋转 (如果应用支持)。
> 
> - 实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
> + 具体来说，_scrcpy_ 会在鼠标位置关于屏幕中心对称的位置上再生成一个“虚拟手指”。
> ```

The last sentence will be easier to understand if changed into sth like:

具体来说，在与鼠标位置关于屏幕中心对称的位置上，_scrcpy_ 会生成一个“虚拟手指”用于模拟点按操作。

2022-03-18 09:33 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@Win7GM I want to emphasize that touch events are generated for BOTH mouse pointer and virtual finger, so I prefer adding a "再“.

2022-03-18 09:44 UTC, Win7GM commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
> @Win7GM I want to emphasize that touch events are generated for BOTH mouse cursor and virtual finger, so I prefer adding a "再“.

@yume-chan I think either way will do but if it should be emphasized I would prefer phrasing it explicitly like:
`具体来说，在鼠标，和与鼠标位置关于屏幕中心对称的位置上，_scrcpy_ 会分别生成一个“虚拟手指”用于模拟点按操作。`

2022-03-18 10:01 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@Win7GM Now the meaning of "virtual finger" now differs from the original English text:

> Concretely, scrcpy generates additional touch events from a "virtual finger" at a location inverted through the center of the screen.

Although it's not unacceptable.

2022-03-18 10:35 UTC, Win7GM commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@yume-chan I start to feel if we remove this “虚拟手指” from the translation it may fit the original meaning better.

2022-03-18 12:24 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@Win7GM I guess that's also fine. Something like 

> 具体来说，Scrcpy 会在鼠标位置，以及鼠标以屏幕中心镜像的位置分别生成触摸事件。

2022-03-18 15:40 UTC, Win7GM commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@yume-chan Agreed.

2022-03-21 03:11 UTC, epiciskandar commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
Hi guys, this is being updated, please check it and we can see if everything applicable now.

2022-03-21 04:33 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@epiciskandar Should be

```markdown
模拟“双指缩放”：<kbd>Ctrl</kbd>+_按下并拖动鼠标_。

准确的说，按住 <kbd>Ctrl</kbd>，然后按下鼠标左键。在松开鼠标左键前，移动鼠标会使屏幕内容相对于屏幕中心缩放
或旋转 (如果应用支持)。

具体来说，Scrcpy 会在鼠标位置，以及鼠标以屏幕中心镜像的位置分别生成触摸事件。
```

I don't like both `准确的说` and `具体来说`, can you guys come up with something better?

2022-03-21 04:48 UTC, Win7GM commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@epiciskandar @yume-chan I think `准确的说` can be removed.
About `具体来说` I think we can alter it into some sentences including sth like `实现原理`.

2022-03-21 07:40 UTC, epiciskandar commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
Might we stray too far from original English version?

2022-03-22 03:34 UTC, Win7GM commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@epiciskandar I think this part will never be altered / will only be altered slightly in the English version and thus I choose to adopt free translation.
The meanings are consistent anyway.

2022-03-22 06:38 UTC, epiciskandar commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
OK, lets' forget unimportant disputes. How about now

2022-03-22 10:05 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
The second half of the second paragraph is still incorrect.

2022-03-22 14:23 UTC, epiciskandar commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
sorry @yume-chan, could you please make another conversation on the updated version? I can't figue out what needs improvements.

2022-03-22 14:53 UTC, yume-chan commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
@rom1v I did the old translation, but when I read it again now, some choices of words are pretty bad.

@epiciskandar's initial change is good, but I want to discuss and improve the whole section taking this opportunity.

@Win7GM and I mostly agreed on the above version, the problem now is @epiciskandar mixed the second and third paragraphs up.

So after changing that or maybe several more discussions after this PR will be good to go.

2022-03-23 11:22 UTC, epiciskandar commented on README.zh-Hans.md
>  实际上，_scrcpy_ 会在关于屏幕中心对称的位置上用“虚拟手指”发出触摸事件。
Docs are important, especially for non-programming skill people, it worth to be patient, and let's make it efficient too, correcting contents is more important than beautify wordings

2022-03-23 14:03 UTC, Win7GM approved these changes

2022-03-23 14:21 UTC, yume-chan approved these changes

2022-03-25 07:40 UTC, rom1v commented
Thank you :+1: Merged: 2edc73e4b80d35acc594adef2d35d99e743befed

2022-03-25 07:40 UTC, closed without merging