Update README.it.md
Genymobile/scrcpy pull request #3151
Opened 2022-03-26 05:20 UTC by alesarrett

Updated the Italian translation of README.md to v1.23 and a few minor modifications.

2022-03-29 14:39 UTC, rom1v commented
Thank you :+1:

@albertopasqualetto as the author of the original translation, do you have some remarks?

2022-03-29 14:40 UTC, rom1v commented on README.it.md
> + - Windows: [download][direct-win64]
No, please keep `README.md#windows`, so that an outdated translated README still points to the latest version to download.

2022-03-29 15:37 UTC, albertopasqualetto requested changes
I added some modifications, please review them (also in "Requisiti" paragraph add "(in inglese)" after opzione aggiuntiva link).

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +Se la connessione cade casualmente, esegui il comando `scrcpy` per riconnetterti. Se il comando dice che non ci sono dispositivi/emulatori trovati, prova ad eseguire `adb connect DEVICE_IP:5555` di n
```suggestion
Se la connessione cade casualmente, esegui il comando `scrcpy` per riconnetterti. Se il comando dice che non ci sono dispositivi/emulatori trovati, prova ad eseguire `adb connect DEVICE_IP:5555` di nuovo, e poi `scrcpy` come al solito. Se dice ancora che non ne ha trovato nessuno, prova ad eseguire `adb disconnect` e poi esegui di nuovo questi due comandi.
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +```
```suggestion
```bash
# Seleziona l'unico dispositivo connesso via USB
scrcpy -d             # come adb -d
scrcpy --select-usb   # versione lunga

# Seleziona l'unico dispositivo connesso via TCP/IP
scrcpy -e             # come adb -e
scrcpy --select-tcpip # versione lunga
```
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +Per connettersi a un dispositivo remoto, è possibile collegare un client `adb` locale a un server remoto `adb` (purché usino la stessa versione del protocollo _adb_). ).
```suggestion
Per connettersi a un dispositivo remoto, è possibile collegare un client `adb` locale a un server remoto `adb` (purché usino la stessa versione del protocollo _adb_). 
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +##### SSH tunnel
```suggestion
##### Tunnel SSH
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +```
```suggestion
```bash
# locale  5038 --> remoto  5037
# locale 27183 <-- remoto 27183
ssh -CN -L5038:localhost:5037 -R27183:localhost:27183 tuo_computer_remoto
# tienilo aperto
```
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
>  ```
```suggestion
# locale  5038 --> remoto  5037
# locale 27183 --> remoto 27183
ssh -CN -L5038:localhost:5037 -L27183:localhost:27183 tuo_computer_remoto
# tienilo aperto
```
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +In alternativa scrcpy può simulare una tastiera fisica USB su Android per fornire una migliore esperienza di input (utilizzando [USB HID over AOAv2][hid-aoav2]): la tastiera virtuale è disabilitata e
```suggestion
In alternativa scrcpy può simulare una tastiera fisica USB su Android per fornire una migliore esperienza di input (utilizzando [USB HID con AOAv2][hid-aoav2]): la tastiera virtuale è disabilitata e funziona per tutti i caratteri e IME.
```

suggestion

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +Nota: su Windows, può funzionare solo in [odalità OTG](#otg), non durante il mirroring (non è possibile aprire un dispositivo USB se è già aperto da un altro processo come il daemon adb).
```suggestion
Nota: su Windows, può funzionare solo in [modalità OTG](#otg), non durante il mirroring (non è possibile aprire un dispositivo USB se è già aperto da un altro processo come il daemon adb).
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +Nota: su Windows, può funzionare solo in [odalità OTG](#otg), non durante il mirroring (non è possibile aprire un dispositivo USB se è già aperto da un altro processo come il daemon adb).
```suggestion
Nota: su Windows, può funzionare solo in [odalità OTG](#otg), non durante il mirroring (non è possibile aprire un dispositivo USB se è già aperto da un altro processo come il demone adb).
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +In questa modalità, gli eventi i pressione originali (scancodes) sono inviati al dispositivo, indipendentemente dalla mappatura dei tasti dell'host. Pertanto, se il layout della tua tastiera non corr
```suggestion
In questa modalità, gli eventi i pressione originali (scancodes) sono inviati al dispositivo, indipendentemente dalla mappatura dei tasti dell'host. Pertanto, se il layout della tua tastiera non corrisponde, deve essere configurato sul dispositivo Android, in Impostazioni → Sistema → Lingue e input → [Tastiera fisica] (in inglese).
```

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +Solo il file README in inglese ([README.md](README.md)) è sempre aggiornato.
```suggestion

```
It does not have to be in translation

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +Se incontri un bug, per favore leggi prima le [FAQ], poi apri un [issue].
```suggestion
Se incontri un bug, per favore leggi prima le [FAQ], poi apri una [issue].
```

I think it is femenine

2022-03-29 15:37 UTC, albertopasqualetto commented on README.it.md
> +4. Abilita adb su TCP/IP sul tuo dispositivo: `adb tcpip 5555`.
```suggestion
4. Abilita adb via TCP/IP sul tuo dispositivo: `adb tcpip 5555`.
```

2022-04-10 12:19 UTC, rom1v commented
Thank you to both of you.

I applied the changes @albertopasqualetto suggested, the result is here: [`pr3151`](https://github.com/Genymobile/scrcpy/commits/pr3151)

If it's ok for you, I'll merge it.

2022-04-12 22:05 UTC, rom1v commented
@alesarrett ok for you?

2022-04-13 09:15 UTC, alesarrett commented
Yes, of course. Thanks!

2022-04-14 08:12 UTC, rom1v commented
:+1: merged: fc65c6cc4baced6d9758ee54d9fdab57966d09b8

2022-04-14 08:12 UTC, closed without merging

2022-04-14 08:13 UTC, rom1v commented
@albertopasqualetto

> I was wandering if it is better naming tags like [lowlatency] in english or translating them to italian

I don't care, as long as it works :wink: